version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- sh ./initialize.sh
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
